version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/ctdk/goiardi

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS

      - restore_cache:
          keys:
            - v1-pkg-cache

      - run: sudo apt-get update && sudo apt-get install rpm python-sphinx ruby rubygems ruby-dev -y
      - run:
          name: Run 'go test'
          command: go test -v -race ./... 2>&1 | tee ${TEST_RESULTS}/goiardi-test.out

      - run: go build .

      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"
      - store_artifacts:
          path: /tmp/test-results

  package_build:
    docker:
      - image: circleci/golang:1.10
    
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run: sudo apt-get update && sudo apt-get install rpm python-sphinx ruby rubygems ruby-dev -y
      - run: sudo gem install fpm
      - run: go get github.com/ctdk/gox
      - run:
          name: Build packages
          command: /bin/bash packaging.sh
          working_directory: /go/src/github.com/ctdk/goiardi/packaging
      - store_artifacts:
          path: /go/src/github.com/ctdk/goiardi/packaging/artifacts
      - persist_to_workspace:
          root: /go/src/github.com/ctdk/goiardi/packaging
          paths:
            - artifacts

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - package_build:
          requires:
            - build
