version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10.1

    working_directory: /go/src/github.com/ctdk/goiardi

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS

      - restore_cache:
          keys:
            - v1-pkg-cache

      - run: gem install fpm
      - run: sudo apt-get update && sudo apt-get install rpm python-sphinx -y
      - run: go get github.com/ctdk/gox
      - run:
        name: Run 'go test'
        command: go test -v -race ./... 2>&1 | tee ${TEST_RESULTS}/goiardi-test.out

      - run: go build .

      - save_cache:
        key: v1-pkg-cache
        paths:
          - "/go/pkg"
  package:
    working_directory: /go/src/github/ctdk/goiardi/packaging
    steps:
      - run: /bin/bash packaging.sh
  deploy:
    working_directory: /go/src/github/ctdk/goiardi/packaging
    steps:
      - run: /bin/bash deploy.sh

workflows:
  version: 2
  build_package_deploy:
    jobs:
      - build
      - package:
        requires:
          - build
      - deploy:
          requires:
            - package
          filters:
            branches:
              only: releases
